services:
  - type: web
    name: ifri-collection-backend
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DB_NAME
        fromDatabase:
          name: ifri-collection-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ifri-collection-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ifri-collection-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: ifri-collection-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ifri-collection-db
          property: port

databases:
  - name: ifri-collection-db
    databaseName: ifri_collection
    user: root